version: '2'
services:
  catinyuaa-mariadb:
    extends:
      file: mariadb.yml
      service: catinyuaa-mariadb
    volumes:
      - /root/volumes/jhipster/CatinyUAA/mysql/:/var/lib/mysql/
  catinyuaa-redis:
    extends:
      file: redis.yml
      service: catinyuaa-redis
  catinyuaa-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: catinyuaa-elasticsearch
    volumes:
      - /root/volumes/jhipster/CatinyUAA/elasticsearch/:/usr/share/elasticsearch/data/
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_PRIVATE://kafka:9092,LISTENER_PUBLIC://catiny.com:10400
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger,uaa
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
